// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://funwvakgjusbmrjloyvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bnd2YWtnanVzYm1yamxveXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI3ODgsImV4cCI6MjA2OTI4ODc4OH0.xn-BFVohZwnyvd6HMHjPlq9deHWYyDr4_7BD6-nK8Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});